### ISSUE TITLE
Using new GitHub Install - Install issue when choosing Cognito SSO

### ISSUE THREAD

**Issue by MarkVanKerro** [aws-samples/document-translation#90]
Hi

When trying to build selecting Cognito SSO only, at the end of the parameter entries the following error is received, any advise?

/home/cloudshell-user/document-translation/util/installer/src/options.ts:38
                                        mfa: options.appCognitoLocalOptions.app.cognito.localUsers.mfa,
                                             ^
TypeError: Cannot read properties of undefined (reading 'cognito')
    at mapConfig (/home/cloudshell-user/document-translation/util/installer/src/options.ts:38:46)
    at getConfigurationOptions (/home/cloudshell-user/document-translation/util/installer/src/options.ts:76:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (/home/cloudshell-user/document-translation/util/installer/src/main.ts:13:17)

**Comment by philipws** [comment]
Hey @MarkVanKerro this should be resolved by #91 thanks to domaws. You can pull down the latest repo head to get the fix. If it persists please reopen this.
